version: '3.7'
services:
  db-oauth:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: redcoins/oauth-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=oauth
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    networks:
      - private

  app:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - db-oauth
    ports:
      - "80:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - private

networks:
  private:
    driver: bridge

